name: Main workflow
on: push
env: # Set the secret as an input
  github_username: ${{ github.actor }} # Has to be lowercase, otherwise ${{ github.actor }}
  github_password: ${{ secrets.GITHUB_TOKEN }} # Must be made available to the workflow
  git_commit: ${{ github.sha }} # Commit sha
jobs:
  Build:
    runs-on: ubuntu-latest
    container: gradle:6-jdk11
    steps:
      - name: Clone down repository
        uses: actions/checkout@v4       
      - name: Build application
        run: ci/build-app.sh
      - name: Test
        run: ci/unit-test-app.sh
      - uses: actions/upload-artifact@v4
        with: 
          name: code
          path: .
          include-hidden-files: true
  Linting:
    runs-on: ubuntu-latest
    needs: [Build]
    steps:
      - name: Download code
        uses: actions/download-artifact@v4
        with:
          name: code
          path: .
      - name: Run linting
        uses: super-linter/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${ secrets.GITHUB_TOKEN }}
          # Disable linting for now because we are not planning to modify the source files
          DISABLE_ERRORS: true
  Docker-image:
    runs-on: ubuntu-latest
    needs: [Build]
    permissions:
      packages: write
    steps:
    - name: Download code
      uses: actions/download-artifact@v4
      with:
          name: code
          path: .
    # Normalize username to lowercase to comply with docker naming rules
    - name: Normalize GitHub username to lowercase
      run: echo "github_username=${github_username,,}" >> $GITHUB_ENV
      shell: bash
    - name: Show normalized username
      run: echo "Normalized username is $github_username"
    - name: Build docker
      run: bash ci/build-docker.sh
    - name: Push docker
      run: bash ci/push-docker.sh

